app_id             = "http-crud-tutorial"
app_env            = "prod"
region             = "us-east-1"
lambda_package     = "lambda-tf-gitlab.zip"
workspace          = "prod"
domain             = "api.cmcloudlab705.info"
repo_url           = "https://gitlab.com/training-cloud/lambda-tf-gitlab.git"
#AWS_account 
aws_account_id     = "856960422202"
aws_role_name      = "training-gitlab-deploy-role"