app_id             = "http-crud-tutorial"
app_env            = "prod"
region             = "us-east-1"
lambda_package     = "lambda-tf-gitlab.zip"
workspace          = "prod"
domain             = "api.autheracloud.com"
repo_url           = "https://gitlab.com/training-cloud/lambda-tf-gitlab.git"
#AWS_account 
aws_account_id     = "677825414567"
aws_role_name      = "Role_devsecops"